apiVersion: apps/v1
kind: Deployment
metadata:
  name: parallel-test-1
  labels:
    k8s-app: parallel-test-1
spec:
  replicas: 5
  selector:
    matchLabels:
      k8s-app: parallel-test-1
  template:
    metadata:
      labels:
        k8s-app: parallel-test-1
    spec:
      containers:
        - name: test-1
          image: ivukotic/servicex-test:latest
          command: ["python3"]
          args:
            [
              "test_1.py",
              "data18_13TeV:data18_13TeV.periodAllYear.physics_Main.PhysCont.DAOD_PHYS.grp18_v01_p4150",
            ]
            # data18_13TeV:data18_13TeV.periodAllYear.physics_Main.PhysCont.DAOD_PHYS.grp18_v01_p4150 HUGE
            # data15_13TeV:data15_13TeV.00283429.physics_Main.deriv.DAOD_PHYS.r9264_p3083_p4165_tid21568817_00  1447 files
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
