apiVersion: apps/v1
kind: Deployment
metadata:
  name: parallel-test-1
  labels:
    k8s-app: parallel-test-1
spec:
  replicas: 5
  selector:
    matchLabels:
      k8s-app: parallel-test-1
  template:
    metadata:
      labels:
        k8s-app: parallel-test-1
    spec:
      containers:
        - name: test-1
          image: ivukotic/servicex-test:latest
          # imagePullPolicy: IfNotPresent
          command: ["python3"]
          args: ["test_1.py"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
