apiVersion: v1
kind: Pod
metadata:
  name: servicex-test
spec:
  containers:
    - name: servicex-test
      image: ivukotic/servicex-test:latest
      # image: servicex-test:latest
      # pullPolicy: Never
      command:
        - "sleep"
      args: ["36500000"]
