apiVersion: v1
kind: Pod
metadata:
  name: test-transformer1
spec:
  containers:
    - name: servicex-test
      image: sslhep/servicex_func_adl_xaod_transformer:v1.0.0
      command:
        - "sleep"
      args: ["36500000"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
