apiVersion: v1
kind: Pod
metadata:
  name: servicex-test
spec:
  containers:
    - name: servicex-test
      image: ivukotic/servicex-test:latest
      # image: servicex-test:latest
      # pullPolicy: Never
      # command: ["/run.sh"]
      command: ["sleep"]
      args: ["36500000"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
