apiVersion: v1
kind: Pod
metadata:
  name: sequential-test
spec:
  containers:
    - name: sequential-test
      image: ivukotic/servicex-test:latest
      # image: servicex-test:latest
      # pullPolicy: Never
      command: ["/bin/bash"]
      args: ["/run.sh"]
      # command: ["sleep"]
      # args: ["36500000"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
