apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-test
  labels:
    k8s-app: single-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: single-test
  template:
    metadata:
      labels:
        k8s-app: single-test
    spec:
      containers:
        - name: test-1
          image: ivukotic/servicex-test:latest
          # imagePullPolicy: IfNotPresent
          command: ["python3"]
          args:
            [
              "test_1.py",
              "data15_13TeV:data15_13TeV.00283429.physics_Main.deriv.DAOD_PHYS.r9264_p3083_p4165_tid21568817_00",
            ]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
