apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-test-uproot
  namespace: default
  labels:
    k8s-app: single-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: single-test
  template:
    metadata:
      labels:
        k8s-app: single-test
    spec:
      containers:
        - name: test-1
          image: ivukotic/servicex-test:latest
          # imagePullPolicy: IfNotPresent
          command: ["python3"]
          args:
            [
              "test_101.py",
              "root://eospublic.cern.ch//eos/opendata/atlas/OutreachDatasets/2020-01-22/4lep/MC/mc_345060.ggH125_ZZ4lep.4lep.root",
              "uproot-af",
            ]
            # "data15_13TeV:data15_13TeV.00282784.physics_Main.deriv.DAOD_PHYSLITE.r9264_p3083_p4165_tid21568807_00",
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "1000m"
