apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-test2
  labels:
    k8s-app: single-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: single-test
  template:
    metadata:
      labels:
        k8s-app: single-test
    spec:
      containers:
        - name: test-1
          image: ivukotic/servicex-test:latest
          # imagePullPolicy: IfNotPresent
          command: ["python3"]
          args:
            [
              "test_1.py",
              "data18_13TeV:data18_13TeV.periodB.physics_Main.PhysCont.DAOD_PHYS.grp18_v01_p4150",
              "xaod-af",
            ]
            # data18_13TeV:data18_13TeV.periodAllYear.physics_Main.PhysCont.DAOD_PHYS.grp18_v01_p4150 HUGE
            # data18_13TeV:data18_13TeV.periodB.physics_Main.PhysCont.DAOD_PHYS.grp18_v01_p4150 one period
            # data15_13TeV:data15_13TeV.00283429.physics_Main.deriv.DAOD_PHYS.r9264_p3083_p4165_tid21568817_00  1447 files
            # xaod-test2
            # xaod-af
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
